[package]
name = "lagodb-connectors"
version = { workspace = true }
publish = false
license = { workspace = true }
description = "LagoDB connector FDW skeleton."
homepage = "https://github.com/robertmu/pg-lakebase"
repository = "https://github.com/robertmu/pg-lakebase"
edition = { workspace = true }
rust-version = { workspace = true }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [] }

[features]
default = ["pg17"]
pg16 = ["pgrx/pg16", "lagodb-core/pg16", "pg-arrow-conv/pg16"]
pg17 = ["pgrx/pg17", "lagodb-core/pg17", "pg-arrow-conv/pg17"]

[dependencies]
apache-avro = { version = "0.21", default-features = false, features = ["snappy", "zstandard"] }
arrow-schema = "58"
arrow-array = "58"
arrow-arith = "58"
arrow-ord = "58"
bytes = "1"
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }
flate2 = "1"
pgrx = { workspace = true }
lagodb-core = { path = "../lagodb-core", default-features = false }
pg-arrow-conv = { path = "../pg-arrow-conv", default-features = false }
lagodb-storage = { workspace = true }
parquet = { version = "58", default-features = false, features = ["arrow", "snap", "zstd"] }
serde = "1"
serde_json = { version = "1", features = ["arbitrary_precision", "raw_value"] }
thiserror = "1.0"
uuid = { version = "1.16.0", features = ["v7"] }
zstd = "0.13"
