use std::cell::{Cell, RefCell};
use std::collections::HashMap;
use std::rc::Rc;

use iceberg_lite::catalog::{NamespaceIdent, TableIdent};
use iceberg_lite::io::FileIO;
use iceberg_lite::spec::{DataFile, TableMetadata};
use iceberg_lite::table::Table;
use iceberg_lite::transaction::Transaction;
use pg_lakehouse_core::diag;
use pgrx::pg_sys;
use pgrx::prelude::PgSqlErrorCode;

use crate::catalog::iceberg_catalog::IcebergCatalog;

use crate::catalog::iceberg_metadata::{IcebergMetadata, IcebergMetadataError};
use crate::error::{IcebergError, IcebergResult};
use crate::gucs;
use pg_lakehouse_core::access::xact::{self, TransactionResource};

/// Represents the metadata location state for a single table within a transaction.
#[derive(Debug, Clone)]
pub struct TableMetadataState {
    /// Table OID
    pub relid: pg_sys::Oid,

    /// Namespace OID
    pub namespace_oid: pg_sys::Oid,

    /// Relation Number (RelFileNode)
    pub rel_num: pg_sys::RelFileNumber,

    /// The metadata location when this transaction FIRST accessed the table
    /// This is used as the absolute base for determining if we need to rebase
    pub initial_base_metadata_location: Option<String>,

    /// Current metadata location in this transaction (generated by our latest statement)
    pub current_metadata_location: Option<String>,

    /// The global metadata location that current_metadata_location was based on.
    /// Used to optimize subsequent rebase checks; if global hasn't moved, we don't need to re-rebase.
    pub last_base_metadata_location: Option<String>,

    /// Accumulated data files from all statements in this transaction
    /// effectively: accumulated_data_files = [Stmt1_Files, Stmt2_Files, ...]
    pub accumulated_data_files: Vec<DataFile>,

    /// Cached FileIO for final commit
    pub file_io: Option<FileIO>,

    /// Transaction nesting level at which this table was first modified
    pub first_modified_at_level: i32,

    /// Stack of state snapshots for rollback support.
    /// Each entry captures the state BEFORE a change at a particular nesting level.
    ///
    /// Tuple format: (nest_level, prev_metadata_location, prev_files_count, prev_last_base)
    /// - `nest_level`: The nesting level where this change occurred
    /// - `prev_metadata_location`: The metadata location BEFORE this change
    /// - `prev_files_count`: The number of accumulated files BEFORE this change
    /// - `prev_last_base`: The last_base_metadata_location BEFORE this change
    pub level_history: Vec<(i32, Option<String>, usize, Option<String>)>,
}

impl TableMetadataState {
    /// Create a new state for a table that's being modified for the first time
    pub fn new(
        relid: pg_sys::Oid,
        namespace_oid: pg_sys::Oid,
        rel_num: pg_sys::RelFileNumber,
        nest_level: i32,
        initial_base_metadata_location: Option<String>,
    ) -> Self {
        Self {
            relid,
            namespace_oid,
            rel_num,
            initial_base_metadata_location: initial_base_metadata_location.clone(),
            current_metadata_location: initial_base_metadata_location.clone(),
            last_base_metadata_location: initial_base_metadata_location,
            accumulated_data_files: Vec::new(),
            file_io: None,
            first_modified_at_level: nest_level,
            level_history: Vec::new(),
        }
    }

    /// Record a state change: save current state and apply new changes.
    ///
    /// This function:
    /// 1. Saves the current state to level_history (for potential rollback)
    /// 2. Updates current_metadata_location to the new location
    /// 3. Appends new_data_files to accumulated_data_files (can be empty)
    pub fn record_change(
        &mut self,
        nest_level: i32,
        new_metadata_location: String,
        new_data_files: Vec<DataFile>,
    ) {
        // Push current state to history before updating
        self.level_history.push((
            nest_level,
            self.current_metadata_location.clone(),
            self.accumulated_data_files.len(),
            self.last_base_metadata_location.clone(),
        ));

        self.current_metadata_location = Some(new_metadata_location);
        self.accumulated_data_files.extend(new_data_files);
    }

    /// Rollback to a specific nesting level by removing changes made at or above that level.
    ///
    /// # Arguments
    /// * `target_level` - The nesting level being aborted. All changes at this level
    ///   and above will be rolled back.
    ///
    /// # Example
    /// ```text
    /// Level 1: BEGIN
    /// Level 2: SAVEPOINT sp1 (modification A)
    /// Level 3: SAVEPOINT sp2 (modification B)
    /// ROLLBACK TO sp1: calls rollback_to_level(3)
    ///   -> Removes modification B (level 3)
    ///   -> Keeps modification A (level 2)
    /// ```
    pub fn rollback_to_level(&mut self, target_level: i32) {
        while let Some((level, _, _, _)) = self.level_history.last() {
            if *level >= target_level {
                let (_, prev_meta, prev_files_len, prev_base) =
                    self.level_history.pop().unwrap();
                self.current_metadata_location = prev_meta;
                self.accumulated_data_files.truncate(prev_files_len);
                self.last_base_metadata_location = prev_base;
            } else {
                break;
            }
        }
    }
}

/// Transaction-level metadata location tracker
/// Uses HashMap to track multiple tables being modified in the same transaction
pub struct MetadataLocationTracker {
    /// Map: table OID -> metadata state
    tables: HashMap<pg_sys::Oid, TableMetadataState>,
}

impl MetadataLocationTracker {
    pub fn new() -> Self {
        Self {
            tables: HashMap::new(),
        }
    }

    /// Register a table and record initial state from catalog
    pub fn register_table(
        &mut self,
        relid: pg_sys::Oid,
        namespace_oid: pg_sys::Oid,
        rel_num: pg_sys::RelFileNumber,
        nest_level: i32,
    ) -> IcebergResult<()> {
        if self.tables.contains_key(&relid) {
            return Ok(()); // Already registered
        }

        // Read current state from catalog
        let iceberg_meta = IcebergMetadata::get(relid)?;

        let state = TableMetadataState::new(
            relid,
            namespace_oid,
            rel_num,
            nest_level,
            iceberg_meta.metadata_location,
        );

        self.tables.insert(relid, state);
        Ok(())
    }

    /// Rebase accumulated changes on top of the LATEST global metadata (Read Committed).
    ///
    /// This function implements optimistic concurrency control:
    /// 1. Fetches the latest global metadata location from the catalog.
    /// 2. If global hasn't changed and no new files, returns current location (optimization).
    /// 3. Otherwise, replays all accumulated files + new files on top of the latest global base.
    /// 4. Generates a new intermediate metadata file.
    /// 5. Updates tracker state with new metadata location and files.
    pub fn apply_updates_with_rebase(
        &mut self,
        relid: pg_sys::Oid,
        nest_level: i32,
        new_data_files: Vec<DataFile>,
        file_io: &FileIO,
    ) -> IcebergResult<String> {
        let state = self.tables.get_mut(&relid).ok_or_else(|| {
            IcebergError::MetadataError(IcebergMetadataError::ReadFailed(format!(
                "Table {} not registered in metadata tracker",
                relid
            )))
        })?;

        // Cache FileIO for final commit
        if state.file_io.is_none() {
            state.file_io = Some(file_io.clone());
        }

        // 1. Get Latest Global Metadata
        let current_global = IcebergMetadata::get(relid)?;
        let latest_global_location =
            current_global.metadata_location.ok_or_else(|| {
                IcebergError::MetadataError(IcebergMetadataError::ReadFailed(
                    format!("Metadata location is null for table {}", relid),
                ))
            })?;

        // Optimization: Skip rebase if conditions are met:
        // - No new files to append
        // - Global metadata hasn't changed since our last rebase
        // Result: Current metadata location is still valid, return it immediately
        if new_data_files.is_empty()
            && state.last_base_metadata_location.as_ref()
                == Some(&latest_global_location)
        {
            return state.current_metadata_location.clone().ok_or_else(|| {
                IcebergError::MetadataError(IcebergMetadataError::ReadFailed(
                    format!("Current metadata location is null for table {}", relid),
                ))
            });
        }

        // 2. Load Base Table
        // We use a constructed identifier based on OID to ensure consistency
        let metadata = TableMetadata::read_from(file_io, &latest_global_location)?;
        let base_table = Table::builder()
            .metadata_location(latest_global_location.clone())
            .metadata(metadata)
            .identifier(TableIdent::new(
                NamespaceIdent::new(state.namespace_oid.to_string()),
                state.rel_num.to_string(),
            ))
            .file_io(file_io.clone())
            .build()?;

        // 3. Create Storage-Only Catalog wrapper
        let catalog = IcebergCatalog::with_table_pg(file_io.clone(), &base_table)?;

        // 4. Create Transaction and Apply Changes
        let tx = Transaction::new(&base_table);
        let mut append_action = tx.fast_append();

        // Add previously accumulated files
        if !state.accumulated_data_files.is_empty() {
            append_action =
                append_action.add_data_files(state.accumulated_data_files.clone());
        }
        // Add new files from current statement
        if !new_data_files.is_empty() {
            append_action = append_action.add_data_files(new_data_files.clone());
        }

        // 5. Commit to generate new metadata file
        use iceberg_lite::transaction::ApplyTransactionAction;
        let tx = append_action.apply(tx)?;
        let updated_table = tx.commit(&catalog)?;

        let new_metadata_location = updated_table
            .metadata_location()
            .ok_or(IcebergError::MetadataLocationNull)?
            .to_string();

        // 6. Update Tracker State
        // Update last_base to reflect the global metadata we just rebased on
        // Record the change with new metadata location and data files
        state.last_base_metadata_location = Some(latest_global_location);
        state.record_change(
            nest_level,
            new_metadata_location.clone(),
            new_data_files,
        );

        // Note: initial_base_metadata_location remains unchanged throughout the transaction
        // to track the starting point. For Read Committed isolation, we continuously
        // rebase on the latest global state, allowing us to incorporate concurrent commits.
        Ok(new_metadata_location)
    }

    /// Use this to update state after `dml.rs` successfully generated a metadata file
    /// considering the rebased files.
    pub fn record_change_with_files(
        &mut self,
        relid: pg_sys::Oid,
        nest_level: i32,
        new_metadata_location: String,
        newly_added_files: Vec<DataFile>,
    ) -> IcebergResult<()> {
        let state = self.tables.get_mut(&relid).ok_or_else(|| {
            IcebergError::MetadataError(IcebergMetadataError::NotFound(relid))
        })?;

        state.record_change(nest_level, new_metadata_location, newly_added_files);
        Ok(())
    }

    /// Get the initial base metadata location and accumulated files for a table.
    ///
    /// Returns:
    /// - The metadata location when the transaction FIRST accessed this table
    /// - All data files accumulated during the transaction
    ///
    /// Note: This returns the initial base, not the last rebased base.
    pub fn get_accumulated_state(
        &self,
        relid: pg_sys::Oid,
    ) -> Option<(String, Vec<DataFile>)> {
        self.tables.get(&relid).map(|s| {
            (
                s.initial_base_metadata_location.clone().unwrap_or_default(),
                s.accumulated_data_files.clone(),
            )
        })
    }

    /// Get the current state for a table
    pub fn get_table_state(&self, relid: pg_sys::Oid) -> Option<&TableMetadataState> {
        self.tables.get(&relid)
    }

    /// Commit all changes to the catalog with optimistic concurrency control
    pub fn commit_all(&mut self) -> IcebergResult<()> {
        // Collect keys to avoid borrowing self while iterating
        let table_oids: Vec<pg_sys::Oid> = self.tables.keys().cloned().collect();

        for relid in table_oids {
            let mut retries = 0;
            let max_retries = gucs::max_commit_retries();

            // Loop for optimistic concurrency control (CAS)
            loop {
                if retries > max_retries {
                    return Err(IcebergError::MetadataError(
                        IcebergMetadataError::UpdateFailed(format!(
                            "Failed to commit after {} retries due to concurrent updates",
                            max_retries
                        )),
                    ));
                }
                retries += 1;
                // 0. Get FileIO from state
                let file_io = self
                    .tables
                    .get(&relid)
                    .and_then(|s| s.file_io.clone())
                    .unwrap_or_else(FileIO::memory);

                // 1. Rebase (or check optimization)
                let new_metadata_location = self.apply_updates_with_rebase(
                    relid,
                    1,          // Top-level commit
                    Vec::new(), // No NEW files, just re-applying existing
                    &file_io,
                )?;

                // 2. Get the state to check what base we used
                let state = self.tables.get(&relid).unwrap(); // Safe unwrap
                let last_base = state.last_base_metadata_location.clone();

                // 3. Prepare update
                let mut iceberg_meta = IcebergMetadata::get(relid)?;
                iceberg_meta.metadata_location = Some(new_metadata_location.clone());
                // Set previous_metadata_location to maintain Iceberg's metadata lineage.
                // This points to the global base we rebased from, which becomes the parent
                // of our new metadata file in Iceberg's version chain.
                iceberg_meta.previous_metadata_location = last_base.clone();

                // 4. Attempt Update with CAS (Compare-And-Swap)
                // The update will only succeed if the catalog's current metadata location
                // still matches last_base, ensuring no concurrent modifications occurred.
                match iceberg_meta.update(last_base.as_deref()) {
                    Ok(_) => break, // Success
                    Err(IcebergMetadataError::Conflict) => {
                        // Standard Iceberg Architecture alignment:
                        // - `IcebergMetadata::update` acts as the "Catalog" (Hive), enforcing strict CAS.
                        // - This loop acts as the "Client" (SnapshotProducer), handling the Retry/Rebase.
                        // In Read Committed mode, we MUST rebase Appends to prevent transaction aborts.
                        diag::report_notice(&format!(
                            "Concurrent Iceberg update detected for table {}, rebasing...",
                            relid
                        ));
                        continue;
                    }
                    Err(e) => return Err(IcebergError::MetadataError(e)),
                }
            }
        }
        Ok(())
    }

    /// Rollback all tracked tables to a specific nesting level.
    ///
    /// This performs two cleanup operations:
    /// 1. **Remove** tables that were first modified at or above `target_level`
    ///    (these tables are considered "new" to this subtransaction)
    /// 2. **Rollback** remaining tables' histories to remove changes made at or above `target_level`
    ///    (these tables were modified before and during this subtransaction)
    ///
    /// # Arguments
    /// * `target_level` - The nesting level being aborted
    pub fn rollback_to_level(&mut self, target_level: i32) {
        self.tables.retain(|_, state| {
            if state.first_modified_at_level >= target_level {
                false // Remove tables first modified at this level
            } else {
                // Keep table, but rollback any changes made at this level or above
                state.rollback_to_level(target_level);
                true
            }
        });
    }
}

// Thread-local storage for the metadata tracker
thread_local! {
    static METADATA_TRACKER: RefCell<Option<MetadataLocationTracker>> = const { RefCell::new(None) };
}

/// Wrapper to integrate MetadataLocationTracker with pg-lakehouse-core transaction system
#[derive(Debug)]
pub struct MetadataLocationResource {
    nest_level: Cell<i32>,
}

impl MetadataLocationResource {
    pub fn new(nest_level: i32) -> Self {
        Self {
            nest_level: Cell::new(nest_level),
        }
    }
}

impl TransactionResource for MetadataLocationResource {
    fn nest_level(&self) -> i32 {
        self.nest_level.get()
    }

    fn set_nest_level(&self, level: i32) {
        self.nest_level.set(level);
    }

    fn on_pre_commit(&self) {
        METADATA_TRACKER.with(|tracker| {
            if let Some(tracker) = tracker.borrow_mut().as_mut() {
                // FileIO is now cached in the state, so we don't need to pass it
                if let Err(e) = tracker.commit_all() {
                    // Use report_error to abort the transaction with a specific error code
                    diag::report_error(
                        PgSqlErrorCode::ERRCODE_INTERNAL_ERROR,
                        &format!("Failed to commit metadata locations: {:?}", e),
                    );
                }
            }
        });
    }

    fn on_commit(&self) {
        // Clear the tracker after commit
        METADATA_TRACKER.with(|tracker| {
            *tracker.borrow_mut() = None;
        });
    }

    fn on_abort(&self) {
        // Simply discard the tracker on abort
        // No need to explicitly restore catalog entries since the transaction will rollback
        METADATA_TRACKER.with(|tracker| {
            *tracker.borrow_mut() = None;
        });
    }

    fn on_commit_sub(&self, _current_nest_level: i32) {
        // On subtransaction commit, promote changes to parent level
        // The changes remain in the tracker, we just update nesting level
        // This is handled by the framework's set_nest_level call

        // No action needed here - changes are already in the tracker
        // and will be committed when the top-level transaction commits
    }

    fn on_abort_sub(&self, current_nest_level: i32) {
        // On subtransaction abort, rollback changes made at or above this level.
        //
        // Note: current_nest_level is the level being ABORTED (not the target level).
        // For example, "ROLLBACK TO sp1" at level 2 will abort level 3+, so
        // current_nest_level = 3.
        //
        // This matches pg-lakehouse-core's behavior where resources with nest_level >= current_nest_level
        // are removed from the resource list.
        METADATA_TRACKER.with(|tracker| {
            if let Some(tracker) = tracker.borrow_mut().as_mut() {
                tracker.rollback_to_level(current_nest_level);
            }
        });

        // Resources registered at or above this level will be automatically removed
        // by pg-lakehouse-core's xact.rs framework.
    }
}

/// Initialize the metadata location tracking system
/// Should be called during extension initialization
pub fn init_metadata_tracking() {
    xact::init_xact_callback();
}

/// Ensure the metadata tracker is initialized for the current transaction
fn ensure_tracker_initialized() -> IcebergResult<()> {
    METADATA_TRACKER.with(|tracker| {
        if tracker.borrow().is_none() {
            let new_tracker = MetadataLocationTracker::new();
            *tracker.borrow_mut() = Some(new_tracker);

            // Register with transaction system
            // We register the resource at the top-level (nest_level 1) to ensure it
            // survives any subtransaction aborts and can commit all changes
            // at the end of the top-level transaction.
            let resource = Rc::new(MetadataLocationResource::new(1));
            xact::register_resource(resource);
        }
        Ok(())
    })
}

/// Register a table for metadata tracking
/// Call this when a table is about to be modified
pub fn register_table_for_tracking(
    relid: pg_sys::Oid,
    namespace_oid: pg_sys::Oid,
    rel_num: pg_sys::RelFileNumber,
) -> IcebergResult<()> {
    ensure_tracker_initialized()?;

    let nest_level = unsafe { pg_sys::GetCurrentTransactionNestLevel() };

    METADATA_TRACKER.with(|tracker| {
        if let Some(tracker) = tracker.borrow_mut().as_mut() {
            tracker.register_table(relid, namespace_oid, rel_num, nest_level)
        } else {
            // Should not happen as ensure_tracker_initialized was called
            unreachable!("Tracker not initialized");
        }
    })
}

/// Record a metadata location change with added data files
pub fn record_metadata_change(
    relid: pg_sys::Oid,
    new_metadata_location: String,
    newly_added_files: Vec<DataFile>,
) -> IcebergResult<()> {
    ensure_tracker_initialized()?;

    let nest_level = unsafe { pg_sys::GetCurrentTransactionNestLevel() };

    METADATA_TRACKER.with(|tracker| {
        if let Some(tracker) = tracker.borrow_mut().as_mut() {
            tracker.record_change_with_files(
                relid,
                nest_level,
                new_metadata_location,
                newly_added_files,
            )
        } else {
            unreachable!("Tracker not initialized");
        }
    })
}

/// Process new data files: handle rebase if necessary and record changes.
/// This replaces manual commit in DML.
pub fn process_new_data_files(
    relid: pg_sys::Oid,
    new_data_files: Vec<DataFile>,
    file_io: &FileIO,
) -> IcebergResult<String> {
    ensure_tracker_initialized()?;
    let nest_level = unsafe { pg_sys::GetCurrentTransactionNestLevel() };

    METADATA_TRACKER.with(|tracker| {
        if let Some(tracker) = tracker.borrow_mut().as_mut() {
            tracker.apply_updates_with_rebase(
                relid,
                nest_level,
                new_data_files,
                file_io,
            )
        } else {
            unreachable!("Tracker not initialized");
        }
    })
}

/// Get the current metadata location for a table within the transaction,
/// ensuring we see latest global changes (Read Committed) if table is already tracked.
pub fn get_or_rebase_metadata_location(
    relid: pg_sys::Oid,
    file_io: &FileIO,
) -> IcebergResult<String> {
    ensure_tracker_initialized()?;
    let nest_level = unsafe { pg_sys::GetCurrentTransactionNestLevel() };

    METADATA_TRACKER.with(|tracker| {
        let mut tracker_borrow = tracker.borrow_mut();
        let tracker = tracker_borrow.as_mut().unwrap();

        if tracker.get_table_state(relid).is_some() {
            // Already tracked (modified in this transaction).
            // Trigger rebase to incorporate any concurrent commits from other transactions
            // that occurred since our last statement in this transaction.
            tracker.apply_updates_with_rebase(relid, nest_level, Vec::new(), file_io)
        } else {
            // Not tracked (not modified yet in this transaction).
            // Just return latest from catalog - this respects statement-level snapshots in RC mode.
            let iceberg_meta = IcebergMetadata::get(relid)?;
            iceberg_meta
                .metadata_location
                .ok_or(IcebergError::MetadataLocationNull)
        }
    })
}
