[package]
name = "pg-lakebase-core"
version = { workspace = true }
authors = ["Robert Mu. https://github.com/robertmu"]
license = { workspace = true }
description = "Postgres Table Access Method framework in Rust."
homepage = "https://github.com/robertmu/pg-lakebase"
repository = "https://github.com/robertmu/pg-lakebase"
categories = ["database"]
keywords = ["database", "postgres", "postgresql", "extension", "access-method"]
edition = { workspace = true }
rust-version = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [] }

[features]
default = ["pg17"]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16"]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17"]
# Enables `#[doc(hidden)]` test hooks consumed by `pg-lakebase-core-tests`.
pg_test = []

[dependencies]
pgrx = { workspace = true }
thiserror = "1.0.63"
pg-lakebase-macros = { version = "0.1.0", path = "../pg-lakebase-macros" }
pg-lakebase-storage = { path = "../pg-lakebase-storage" }
bytes = "1.10"
uuid = { version = "1.16", features = ["v7"] }

[dev-dependencies]
pgrx-tests = { workspace = true }
proptest = "1.5"

[build-dependencies]
cc = "1"
pgrx-pg-config = "=0.18.1"

[package.metadata.docs.rs]
features = ["pg17"]
no-default-features = true
# Enable `#[cfg(docsrs)]` (https://docs.rs/about/builds#cross-compiling)
rustc-args = ["--cfg", "docsrs"]
